/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-central-1',
  aws_cognito_identity_pool_id: 'eu-central-1:27b84ef9-1a0d-4e22-a5b7-3a2658947169',
  aws_cognito_region: 'eu-central-1',
  aws_user_pools_id: 'eu-central-1_xMipHl1so',
  aws_user_pools_web_client_id: '3mh2tg4254pl8p9pi5s1adbq8k',
  oauth: {
    domain: '5cdsc07ywdz2-dev.auth.eu-central-1.amazoncognito.com',
    scope: ['phone', 'email', 'openid', 'profile', 'aws.cognito.signin.user.admin'],
    redirectSignIn: 'https://hukus.net/',
    redirectSignOut: 'https://hukus.net/',
    responseType: 'code'
  },
  federationTarget: 'COGNITO_USER_POOLS'
};

export default awsmobile;
