/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:b45c31e8-0b5d-4d4c-b7b8-5594dfd56fdd",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_Cnh8HN2wE",
    "aws_user_pools_web_client_id": "140mlac2mfnlafj4scd88l8iph",
    "oauth": {
        "domain": "hukusnet18798d3e-18798d3e-dev.auth.eu-central-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://hukus.net/",
        "redirectSignOut": "https://hukus.net/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
