/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:82f1f99f-473c-4a05-a936-d50a3c6f6eca",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_xpnH61ZDb",
    "aws_user_pools_web_client_id": "6uigmcv72l1vgtu6o1ailosrvs",
    "oauth": {
        "domain": "hukusnet-staging.auth.eu-central-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
