# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # - name: Configure amplify
      #   run: |
      #     aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID  }}
      #     aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
      #     aws configure set default.region us-east-1
      #     npm install -g @aws-amplify/cli@4.32.1 --unsafe-perm=true
      #     amplify --version
      #     amplify init // change to bash version
      #     amplify pull --yes

      - name: Yarn install
        run: |
          yarn install --frozen-lockfile

      - name: Sapper Export
        run: |
          yarn export

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.hukus.net
          username: ${{ secrets.ftp_login }}
          password: ${{ secrets.ftp_pw }}
          local-dir: __sapper__/export/
          server-dir: public_html/
          log-level: standard
